name: mlflow_churn_env # Nama lingkungan Conda
channels:
  - defaults
  - conda-forge # Disarankan untuk akses paket yang lebih luas
dependencies:
  - python=3.9 # Versi Python yang konsisten
  - pandas
  - scikit-learn
  - numpy
  - mlflow
  - pip
  - pip:
    - ipykernel # Opsional, berguna untuk pengembangan lokal di Jupyter
