name: MLflow Churn Prediction Training

on:
  push:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.get_run_id.outputs.run_id }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          activate-environment: mlflow_churn_env 

      - name: Configure MLflow Tracking (Optional)
        run: |
          set -e
          echo "Using local MLflow tracking (mlruns/ directory)."
          # export MLFLOW_TRACKING_URI=http://your-server:5000

      - name: Run MLflow Project
        run: |
          set -e
          rm -rf mlruns
          conda run -n mlflow_churn_env mlflow run MLProject/ -e train_model

      - name: Get Run ID from mlruns directory
        id: get_run_id
        run: |
          set -e
          EXPERIMENT_DIR="mlruns/0"

          if [ ! -d "$EXPERIMENT_DIR" ]; then
            echo "Error: MLflow experiment directory not found."
            exit 1
          fi

          RUN_DIR=$(find "$EXPERIMENT_DIR" -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p\n' | sort -n | tail -n 1 | awk '{print $2}')

          if [ -z "$RUN_DIR" ]; then
            echo "Error: Could not find latest MLflow run directory."
            exit 1
          fi

          run_id=$(basename "$RUN_DIR")
          echo "Extracted Run ID: $run_id"

          if [[ "$run_id" == "datasets" || -z "$run_id" ]]; then
            echo "Invalid run ID: $run_id"
            exit 1
          fi

          echo "run_id=$run_id" >> $GITHUB_OUTPUT

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: train_model

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          activate-environment: mlflow_churn_env

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Debug Run ID
        run: |
          echo "Run ID received: ${{ needs.train_model.outputs.run_id }}"

      - name: Build and Push MLflow Model Docker Image
        run: |
          set -e
          MLFLOW_RUN_ID="${{ needs.train_model.outputs.run_id }}"

          if [ -z "$MLFLOW_RUN_ID" ] || [ "$MLFLOW_RUN_ID" == "datasets" ]; then
            echo "Error: Invalid MLflow Run ID: $MLFLOW_RUN_ID"
            exit 1
          fi

          echo "Building Docker image from model at run ID: $MLFLOW_RUN_ID"

          # Step 1: Build Docker image from MLflow model
          conda run -n mlflow_churn_env mlflow models build-docker \
            --model-uri "runs:/$MLFLOW_RUN_ID/model" \
            --name churn-prediction-model

          # Step 2: Tag image for DockerHub
          docker tag churn-prediction-model:latest ibrahimakbararsanata/churn-prediction-model:latest

          # Step 3: Push image to DockerHub
          docker push ibrahimakbararsanata/churn-prediction-model:latest
