name: MLflow Churn Prediction Training

on:
  push:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.run_mlflow.outputs.run_id }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          activate-environment: mlflow_churn_env 

      - name: Configure MLflow Tracking (Optional)
        run: |
          echo "MLflow tracking configuration complete (if any)."
          # export MLFLOW_TRACKING_URI=http://your-mlflow-server:5000

      - name: Run MLflow Project and Get Run ID
        id: run_mlflow
        run: |
          rm -rf mlruns

          conda run -n mlflow_churn_env mlflow run MLProject/ -e train_model 2>&1

          RUN_DIR=$(find mlruns/0 -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p\n' | sort -n | tail -n 1 | awk '{print $2}')
          
          if [ -z "$RUN_DIR" ]; then
              echo "Error: Could not find MLflow run directory. Cannot extract Run ID."
              exit 1
          fi
          
          run_id=$(basename "$RUN_DIR")
          echo "Detected MLflow Run ID: $run_id"
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: train_model

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          activate-environment: mlflow_churn_env

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push MLflow Model Docker Image
        run: |
          MLFLOW_RUN_ID="${{ needs.train_model.outputs.run_id }}"
          
          if [ -z "$MLFLOW_RUN_ID" ]; then
            echo "Error: MLflow Run ID not found from previous job. Cannot build Docker image."
            exit 1
          fi

          echo "Building Docker image for MLflow Run ID: $MLFLOW_RUN_ID"
          
          # Step 1: Build Docker image from MLflow
          conda run -n mlflow_churn_env mlflow models build-docker \
            --model-uri "runs:/$MLFLOW_RUN_ID/model" \
            --name churn-prediction-model

          # Step 2: Tag image for DockerHub
          docker tag churn-prediction-model:latest ibrahimakbararsanata/churn-prediction-model:latest

          # Step 3: Push image to DockerHub
          docker push ibrahimakbararsanata/churn-prediction-model:latest
