name: MLflow Churn Prediction Training # Nama workflow di GitHub Actions

on:
  push:
    branches:
      - main # Workflow akan berjalan setiap kali ada push ke cabang 'main'

jobs:
  train_model:
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu terbaru yang disediakan GitHub

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Mengambil kode repositori Anda

      - name: Set up Conda Environment
        # Action ini akan membuat lingkungan Conda DAN mengaktifkannya untuk langkah-langkah berikutnya.
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9 # Pastikan ini cocok dengan versi di conda.yaml
          environment-file: MLProject/conda.yaml # Path ke file conda.yaml Anda
          # auto-activate-base: false # Tidak perlu lagi karena kita akan mengaktifkan lingkungan spesifik
          activate-environment: mlflow_churn_env # <--- PENTING: Aktifkan lingkungan ini secara otomatis

      - name: Run MLflow Project
        # Karena 'activate-environment' sudah mengaktifkan lingkungan,
        # kita tidak perlu lagi 'conda activate' secara manual di sini.
        # Tetap gunakan 'shell: bash -l {0}' untuk kompatibilitas Conda yang lebih baik.
        shell: bash -l {0}
        run: |
          # conda activate mlflow_churn_env # <--- BARIS INI TIDAK LAGI DIPERLUKAN
          mlflow run MLProject/ -e train_model # Menjalankan proyek MLflow dari folder MLProject/

      - name: Upload Confusion Matrix as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: confusion-matrix-report
          path: confusion_matrix_Random_Forest_Classifier.csv
