name: MLflow Churn Prediction Training

on:
  push:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.run_mlflow_project.outputs.run_id }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          activate-environment: mlflow_churn_env

      - name: Configure MLflow Tracking (Optional)
        run: |
          echo "MLflow tracking configuration complete (if any)."

      - name: Run MLflow Project and Capture Run ID
        id: run_mlflow_project
        run: |
          # Remove old mlruns directory to avoid confusion with new run IDs
          rm -rf mlruns
          
          MLFLOW_OUTPUT=$(conda run -n mlflow_churn_env mlflow run MLProject/ -e train_model 2>&1)
          
          echo "Full MLflow run output:"
          echo "$MLFLOW_OUTPUT"
          
          RUN_ID=$(echo "$MLFLOW_OUTPUT" | grep -E "Run ID|MLflow Run ID" | awk '{print $NF}' | tail -n 1)
          
          if [ -z "$RUN_ID" ]; then
              echo "Error: Could not extract MLflow Run ID from the mlflow run output."
              echo "Attempting to find it from the filesystem as a fallback..."
              RUN_DIR=$(ls -td mlruns/0/*/ | head -1)
              if [ -z "$RUN_DIR" ]; then
                  echo "Error: Fallback also failed. Cannot extract Run ID."
                  exit 1
              fi
              RUN_ID=$(basename "$RUN_DIR")
          fi
          
          echo "Detected MLflow Run ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Upload MLflow Tracking Data (mlruns)
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-tracking-data # Nama artefak
          path: mlruns/ # Direktori yang akan diunggah
          retention-days: 1
        if: always()


  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: train_model
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          activate-environment: mlflow_churn_env

      # PERUBAHAN KRITIS DI SINI
      - name: Download MLflow Tracking Data (mlruns)
        uses: actions/download-artifact@v4
        with:
          name: mlflow-tracking-data
          path: mlruns/ # Ubah path download ke mlruns/ agar folder mlruns/ terbentuk kembali

      - name: Verify mlruns directory after download
        run: |
          echo "Contents of current directory after download:"
          ls -la
          echo "Contents of mlruns directory:"
          ls -la mlruns/ # Ini sekarang seharusnya berfungsi
          if [ ! -d "mlruns" ]; then
            echo "Error: mlruns directory was not downloaded or is missing!"
            exit 1
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push MLflow Model Docker Image
        run: |
          MLFLOW_RUN_ID="${{ needs.train_model.outputs.run_id }}"
          
          echo "Debugging: Value of MLFLOW_RUN_ID: $MLFLOW_RUN_ID"
          
          if [ -z "$MLFLOW_RUN_ID" ]; then
            echo "Error: MLflow Run ID not found from previous job. Cannot build Docker image."
            exit 1
          fi

          echo "Building Docker image for MLflow Run ID: $MLFLOW_RUN_ID"
          
          conda run -n mlflow_churn_env mlflow models build-docker \
            --model-uri "runs:/$MLFLOW_RUN_ID/model" \
            --name ibrahimakbararsanata/churn-prediction-model:latest

          docker push ibrahimakbararsanata/churn-prediction-model:latest
