name: MLflow Churn Prediction Training

on:
  push:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.run_mlflow.outputs.run_id }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          activate-environment: mlflow_churn_env 

      - name: Configure MLflow Tracking (Opsional)
        run: |
          # Jika Anda menggunakan MLflow Tracking Server eksternal, konfigurasikan di sini.
          # Contoh: export MLFLOW_TRACKING_URI=http://your-mlflow-tracking-server:5000
          # Jika Anda tidak mengatur MLFLOW_TRACKING_URI, MLflow akan menggunakan direktori mlruns lokal secara default.
          echo "MLflow tracking configuration complete (if any)."

      - name: Run MLflow Project and Get Run ID
        id: run_mlflow
        run: |
          # Hapus direktori mlruns lama agar tidak salah mengambil run ID
          rm -rf mlruns
          
          # Jalankan MLflow project
          # Hapus --no-tracking-uri di sini
          conda run -n mlflow_churn_env mlflow run MLProject/ -e train_model 2>&1

          # --- BAGIAN KRITIS: Ekstraksi Run ID yang lebih robust ---
          RUN_DIR=$(find mlruns/0 -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p\n' | sort -n | tail -n 1 | awk '{print $2}')
          
          if [ -z "$RUN_DIR" ]; then
              echo "Error: Could not find MLflow run directory. Cannot extract Run ID."
              exit 1
          fi
          
          run_id=$(basename "$RUN_DIR")
          # --- AKHIR BAGIAN KRITIS ---

          echo "Detected MLflow Run ID: $run_id"
          echo "run_id=$run_id" >> $GITHUB_OUTPUT 

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: train_model
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          activate-environment: mlflow_churn_env

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push MLflow Model Docker Image
        run: |
          MLFLOW_RUN_ID="${{ needs.train_model.outputs.run_id }}"
          
          if [ -z "$MLFLOW_RUN_ID" ]; then
            echo "Error: MLflow Run ID not found from previous job. Cannot build Docker image."
            exit 1
          fi

          echo "Building Docker image for MLflow Run ID: $MLFLOW_RUN_ID"
          
          conda run -n mlflow_churn_env mlflow models build-docker \
            --model-uri "runs:/$MLFLOW_RUN_ID/model" \
            --name ibrahimakbararsanata/churn-prediction-model \
            --tag latest

          docker push ibrahimakbararsanata/churn-prediction-model:latest
