name: MLflow Churn Prediction Training

on:
  push:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.10.10
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Run MLflow Project
        # Penting: Gunakan 'shell: bash -l {0}' atau 'shell: bash --login -eo pipefail {0}'
        # untuk memastikan lingkungan Conda diinisialisasi dengan benar.
        shell: bash -l {0} # Atau shell: bash --login -eo pipefail {0}
        run: |
          conda activate mlflow_churn_env
          mlflow run MLProject/ -e train_model
